// src/shared/dataGhost/keywordPool.ts
//
// Baza fraz dla silnika szumu DataGhost (Moduł A). Wydzielona z background.ts i
// znacznie rozszerzona: im większa i bardziej zróżnicowana pula, tym trudniej
// algorytmom telemetrycznym odfiltrować sztuczny ruch po powtarzalnym wzorcu.
//
// Klucze kategorii są kontraktem ze studiem Wirtualnej Tożsamości
// (shared/virtualIdentityStudio.ts → InterestSpec.noiseCategories). Nie zmieniaj
// nazw kluczy bez aktualizacji tamtego mapowania.

export const KEYWORD_POOL: Record<string, string[]> = {
  cooking: [
    "pasta carbonara recipe",
    "vegan dinner ideas",
    "sourdough bread baking",
    "homemade soup recipes",
    "meal prep for the week",
    "easy stir fry vegetables",
    "slow cooker beef stew",
    "gluten free dessert recipes",
    "how to make fresh pasta",
    "thai green curry recipe",
    "fermentation kimchi guide",
    "best knife skills tutorial",
    "cast iron skillet care",
    "homemade pizza dough recipe",
    "one pot chicken dinner",
    "baking macarons tips",
    "mediterranean diet meals",
    "quick breakfast smoothie bowls",
    "cooking rice perfectly stovetop",
    "spice blends from scratch",
    "low carb lunch ideas",
    "authentic ramen broth recipe",
    "grilling vegetables marinade",
    "homemade ice cream no churn",
  ],
  travel: [
    "best beaches in europe",
    "budget backpacking tips",
    "hiking trails national parks",
    "solo travel safety guide",
    "packing light for trips",
    "cheap flights search tips",
    "digital nomad destinations",
    "road trip route planner",
    "visa requirements tourists",
    "hidden gems in portugal",
    "train travel across europe",
    "best travel insurance compare",
    "off season travel deals",
    "weekend city break ideas",
    "campervan road trip guide",
    "northern lights best places",
    "street food markets asia",
    "scuba diving beginner spots",
    "travel photography tips",
    "long haul flight comfort",
    "island hopping greece guide",
    "mountain hiking gear checklist",
    "affordable luxury hotels",
    "overnight train sleeper tips",
  ],
  technology: [
    "open source projects 2024",
    "linux command line tips",
    "smart home diy automation",
    "raspberry pi projects",
    "programming best practices",
    "self hosted apps guide",
    "mechanical keyboard reviews",
    "docker compose tutorial",
    "home network setup guide",
    "python data scripting basics",
    "rust vs go performance",
    "local llm running guide",
    "nas backup strategy",
    "vscode extensions productivity",
    "git workflow best practices",
    "wifi 6 router comparison",
    "soldering for beginners",
    "3d printing first project",
    "kubernetes basics explained",
    "api design rest principles",
    "regex cheat sheet examples",
    "ssd vs hdd reliability",
    "cybersecurity home network",
    "esp32 microcontroller projects",
  ],
  fitness: [
    "morning workout routine beginners",
    "yoga poses for flexibility",
    "running plan for 5k",
    "bodyweight exercise guide",
    "stretching after workout",
    "kettlebell full body workout",
    "couch to 10k program",
    "mobility drills for hips",
    "strength training at home",
    "marathon training schedule",
    "hiit workout no equipment",
    "proper deadlift form guide",
    "post run recovery routine",
    "pull up progression plan",
    "cycling training zones",
    "swimming technique freestyle",
    "core stability exercises",
    "rest day active recovery",
    "warm up before lifting",
    "calisthenics skills roadmap",
    "foam rolling techniques",
    "best running shoes guide",
  ],
  gardening: [
    "indoor houseplant care guide",
    "vegetable garden beginners",
    "composting at home tips",
    "balcony container gardening",
    "herb garden kitchen windowsill",
    "raised bed soil mix",
    "propagating succulents guide",
    "tomato growing tips",
    "pollinator friendly plants",
    "pruning fruit trees winter",
    "no dig garden method",
    "seed starting indoors",
    "drought tolerant garden plants",
    "monstera plant care",
    "rainwater harvesting garden",
    "companion planting chart",
    "lawn care without chemicals",
    "growing chillies from seed",
    "vertical garden ideas small",
    "overwintering plants tips",
  ],
  science: [
    "space exploration news",
    "climate change facts overview",
    "biology cell types explained",
    "astronomy beginner telescope",
    "physics everyday life examples",
    "quantum computing explained simply",
    "james webb telescope images",
    "human genome research news",
    "renewable energy breakthroughs",
    "ocean deep sea creatures",
    "neuroscience memory formation",
    "periodic table elements guide",
    "black holes explained",
    "evolution natural selection basics",
    "vaccines how they work",
    "particle physics for beginners",
    "geology plate tectonics",
    "weather forecasting science",
    "crispr gene editing overview",
    "exoplanet discovery methods",
  ],
  culture: [
    "classic films to watch",
    "music theory basics guitar",
    "modern art movements history",
    "book recommendations fiction",
    "documentary films nature",
    "world mythology comparison",
    "jazz history essential albums",
    "museum exhibitions this year",
    "poetry forms explained",
    "philosophy stoicism introduction",
    "architecture styles guide",
    "foreign films must watch",
    "history ancient rome daily life",
    "vinyl records collecting guide",
    "theatre plays famous list",
    "calligraphy for beginners",
    "renaissance painters overview",
    "language learning techniques",
    "opera for newcomers",
    "street art history graffiti",
  ],
  finance: [
    "personal budgeting tips",
    "saving money grocery shopping",
    "beginner investing guide",
    "frugal living ideas",
    "emergency fund how to start",
    "index funds explained",
    "compound interest calculator",
    "paying off debt strategy",
    "retirement planning basics",
    "credit score improvement tips",
    "tax deductions overview",
    "stock market basics beginners",
    "dividend investing explained",
    "side hustle ideas extra income",
    "real estate investing intro",
    "inflation explained simply",
    "etf vs mutual funds",
    "mortgage refinance guide",
    "freelance invoicing taxes",
    "passive income ideas realistic",
    "high yield savings accounts",
    "financial independence basics",
  ],
  health: [
    "sleep hygiene improvement tips",
    "stress management techniques",
    "nutrition balanced diet basics",
    "mental wellness daily habits",
    "hydration health benefits",
    "intermittent fasting overview",
    "vitamin d deficiency signs",
    "meditation for beginners guide",
    "posture correction exercises",
    "healthy gut microbiome foods",
    "managing screen time eyes",
    "breathing exercises anxiety",
    "magnesium benefits sleep",
    "anti inflammatory foods list",
    "building healthy habits routine",
    "ergonomic desk setup tips",
    "cold shower benefits",
    "reducing sugar intake tips",
    "walking 10000 steps benefits",
    "journaling for mental health",
  ],
  hobbies: [
    "watercolor painting tutorial",
    "landscape photography tips",
    "chess opening strategies",
    "knitting patterns beginners",
    "woodworking projects simple",
    "board games for two players",
    "model building kits guide",
    "fishing knots tutorial",
    "origami beginner instructions",
    "guitar chords for beginners",
    "pottery wheel basics",
    "birdwatching beginner guide",
    "puzzle solving techniques",
    "leather crafting starter",
    "home brewing beer basics",
    "drawing fundamentals practice",
    "rc cars hobby guide",
    "embroidery stitches tutorial",
    "astrophotography setup guide",
    "candle making at home",
    "bullet journal layout ideas",
    "dungeons and dragons starter",
  ],
  // --- Dodatkowe kategorie tła (entropia; nie mapowane bezpośrednio w studiu) ---
  automotive: [
    "electric car range comparison",
    "diy car maintenance basics",
    "best winter tires guide",
    "used car buying checklist",
    "motorcycle beginner gear",
    "car detailing at home",
    "hybrid vs electric cost",
    "engine oil change guide",
    "ev charging at home setup",
    "classic car restoration tips",
  ],
  entertainment: [
    "tv series binge worthy",
    "podcast recommendations 2024",
    "indie video games hidden",
    "stand up comedy specials",
    "anime for beginners list",
    "music festivals this summer",
    "best sci fi novels",
    "trivia night questions ideas",
    "streaming service comparison",
    "concert tickets presale tips",
  ],
  education: [
    "learn a language fast",
    "online courses free certificate",
    "study techniques exams",
    "speed reading methods",
    "note taking systems compared",
    "memory palace technique",
    "math fundamentals review",
    "writing essays structure tips",
    "public speaking confidence",
    "critical thinking exercises",
  ],
  shopping: [
    "black friday deals guide",
    "minimalist wardrobe essentials",
    "best value smartphones",
    "sustainable clothing brands",
    "home decor budget ideas",
    "kitchen gadgets worth it",
    "headphones comparison review",
    "ergonomic office chair guide",
    "gift ideas under 50",
    "secondhand shopping tips",
  ],
}

/** Wszystkie klucze kategorii dostępne w puli. */
export const ALL_CATEGORIES: string[] = Object.keys(KEYWORD_POOL)

/** Czy dany identyfikator jest realną kategorią z puli. */
export function isKnownCategory(category: string): boolean {
  return Object.prototype.hasOwnProperty.call(KEYWORD_POOL, category)
}
