// src/shared/emailAlias.ts
// Moduł D: Generowanie aliasów e-mail (Identity Masking).
// Integracja z SimpleLogin API + fallback na generowanie aliasów offline.

import type { EmailAlias, GenerateAliasResponse } from "../types";
import { STORAGE_KEYS } from "../types";
import { loadEncrypted, saveEncrypted } from "./storage";

// ─── Stałe ──────────────────────────────────────────────────────────────────

const SIMPLELOGIN_API_BASE = "https://app.simplelogin.io/api";

// ─── API Tokens ─────────────────────────────────────────────────────────────

interface ApiTokens {
	simplelogin?: string;
}

/**
 * Pobiera zapisane tokeny API (zaszyfrowane w storage).
 */
async function getApiTokens(): Promise<ApiTokens> {
	const tokens = await loadEncrypted<ApiTokens>(STORAGE_KEYS.API_TOKENS);
	return tokens ?? {};
}

/**
 * Zapisuje tokeny API (zaszyfrowane).
 */
export async function saveApiToken(
	provider: keyof ApiTokens,
	token: string,
): Promise<void> {
	const tokens = await getApiTokens();
	tokens[provider] = token;
	await saveEncrypted(STORAGE_KEYS.API_TOKENS, tokens);
}

// ─── SimpleLogin Integration ────────────────────────────────────────────────

/**
 * Generuje nowy alias e-mail via SimpleLogin API.
 *
 * @param apiToken - Klucz API SimpleLogin.
 * @returns Nowy EmailAlias lub null w przypadku błędu.
 */
async function createSimpleLoginAlias(
	apiToken: string,
): Promise<EmailAlias | null> {
	try {
		const response = await fetch(`${SIMPLELOGIN_API_BASE}/alias/random/new`, {
			method: "POST",
			headers: {
				Authentication: apiToken,
				"Content-Type": "application/json",
			},
			body: JSON.stringify({
				note: "Generated by PrivacyMyst",
			}),
		});

		if (!response.ok) {
			console.warn(
				`[PrivacyMyst] SimpleLogin API error: ${response.status} ${response.statusText}`,
			);
			return null;
		}

		const data = (await response.json()) as {
			id: number;
			email: string;
		};

		return {
			id: String(data.id),
			alias: data.email,
			createdAt: Date.now(),
			isActive: true,
			source: "simplelogin",
		};
	} catch (err) {
		console.warn("[PrivacyMyst] SimpleLogin request failed:", err);
		return null;
	}
}

// ─── Offline Fallback ───────────────────────────────────────────────────────

/**
 * Generuje losowy alias e-mail offline (nie wymaga API).
 * Format: privacymyst-<random>@privacymyst.mask
 *
 * Nie jest to prawdziwy adres — służy jako placeholder
 * lub do wypełniania formularzy fałszywymi danymi.
 */
function generateOfflineAlias(): EmailAlias {
	const randomPart = crypto.randomUUID().slice(0, 8);
	const domains = [
		"privacymyst.mask",
		"privacymyst.shield",
		"phantom.mask",
		"ghost.null",
	];
	const domain = domains[Math.floor(Math.random() * domains.length)];

	return {
		id: crypto.randomUUID(),
		alias: `privacymyst-${randomPart}@${domain}`,
		createdAt: Date.now(),
		isActive: true,
		source: "offline",
	};
}

// ─── Persystencja aliasów ───────────────────────────────────────────────────

/** Pobiera listę zapisanych aliasów z zaszyfrowanego storage. */
export async function getStoredAliases(): Promise<EmailAlias[]> {
	const stored = await chrome.storage.local.get(STORAGE_KEYS.EMAIL_ALIASES);
	return (stored[STORAGE_KEYS.EMAIL_ALIASES] as EmailAlias[]) ?? [];
}

/** Zapisuje listę aliasów do storage. */
async function saveAliases(aliases: EmailAlias[]): Promise<void> {
	await chrome.storage.local.set({
		[STORAGE_KEYS.EMAIL_ALIASES]: aliases,
	});
}

// ─── API publiczne ──────────────────────────────────────────────────────────

/**
 * Generuje nowy alias e-mail.
 *
 * Strategia:
 * 1. Jeśli dostępny token SimpleLogin → użyj API.
 * 2. W przeciwnym razie → wygeneruj alias offline.
 *
 * Alias jest automatycznie zapisywany w storage.
 */
export async function generateAlias(): Promise<EmailAlias> {
	const tokens = await getApiTokens();
	let alias: EmailAlias | null = null;

	// Próbuj SimpleLogin
	if (tokens.simplelogin) {
		alias = await createSimpleLoginAlias(tokens.simplelogin);
	}

	// Fallback: offline
	if (!alias) {
		alias = generateOfflineAlias();
	}

	// Zapisz alias w storage
	const existing = await getStoredAliases();
	existing.unshift(alias);
	await saveAliases(existing);

	return alias;
}

/**
 * Pobiera listę wszystkich wygenerowanych aliasów.
 */
export async function listAliases(): Promise<EmailAlias[]> {
	return getStoredAliases();
}

/**
 * Wysyła wiadomość GENERATE_ALIAS do background service workera i zwraca
 * wygenerowany alias. Przeznaczona do wywołania z content.ts (Osoba B).
 *
 * Przykład użycia w content.ts:
 * ```ts
 * import { requestAliasGeneration } from "~shared/emailAlias"
 * const alias = await requestAliasGeneration()
 * inputElement.value = alias.alias
 * ```
 */
export async function requestAliasGeneration(): Promise<EmailAlias> {
	const response = (await chrome.runtime.sendMessage({
		type: "GENERATE_ALIAS",
	})) as GenerateAliasResponse;

	if (!response.success) {
		throw new Error(response.error);
	}
	return response.alias;
}

/**
 * Dezaktywuje alias (oznacza jako nieaktywny w lokalnym storage).
 * W przypadku SimpleLogin — próbuje usunąć via API.
 */
export async function deleteAlias(aliasId: string): Promise<boolean> {
	const aliases = await getStoredAliases();
	const index = aliases.findIndex((a) => a.id === aliasId);
	if (index === -1) return false;

	const alias = aliases[index];

	// Jeśli alias pochodzi z SimpleLogin — próbuj usunąć przez API
	if (alias.source === "simplelogin") {
		const tokens = await getApiTokens();
		if (tokens.simplelogin) {
			try {
				await fetch(`${SIMPLELOGIN_API_BASE}/aliases/${alias.id}`, {
					method: "DELETE",
					headers: { Authentication: tokens.simplelogin },
				});
			} catch {
				console.warn("[PrivacyMyst] Failed to delete alias from SimpleLogin API");
			}
		}
	}

	// Usuń z lokalnej listy
	aliases.splice(index, 1);
	await saveAliases(aliases);

	return true;
}
